export const AUTH_ACTION_TYPES = {
  CHECK_USER_SESSION: "auth/CHECK_USER_SESSION",
  GOOGLE_SIGN_IN_START: "auth/GOOGLE_SIGN_IN_START",
  USERNAME_SIGN_IN_START: "auth/USERNAME_SIGN_IN_START",
  SIGN_IN_SUCESS: "auth/SIGN_IN_SUCESS",
  SIGN_IN_FAILED: "auth/SIGN_IN_FAILED",
  SIGN_UP_START: "auth/SIGN_UP_START",
  SIGN_UP_SUCESS: "auth/SIGN_UP_SUCESS",
  SIGN_UP_FAILED: "auth/SIGN_UP_FAILED",
  SIGN_OUT_START: "auth/SIGN_OUT_START",
  SIGN_OUT_SUCESS: "auth/SIGN_OUT_SUCESS",
};
